### ISSUE TITLE
老铁：json自动生成层级导航栏，求助

### ISSUE THREAD

**Issue by Siffre** [892768447/PyQt#10]
![ca1f3882e37169ca06bf15497d9b4dae](https://user-images.githubusercontent.com/12948798/38452475-6f4a0a6e-3a77-11e8-8bcd-e5d76443315a.jpg)

**Comment by 892768447** [comment]
https://github.com/892768447/PyQt/tree/master/Json%E7%94%9F%E6%88%90QTreeWidget
