### ISSUE TITLE
常见问题汇总

### ISSUE THREAD

**Issue by 892768447** [892768447/PyQt#13]

**Comment by 625781186** [comment]
tabwidget 标题 左侧 正字 = listwiget + stackwidget

懒得写文字 ， listwiget是否能居中自行测试

![listwidget属性设置](https://upload-images.jianshu.io/upload_images/10769157-9a0d397e0c5b2fee.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![信号关联[图片上传中...(2.gif-b720cc-1524054389630-0)]
](https://upload-images.jianshu.io/upload_images/10769157-b3d1d9d13c9aedfa.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![2.gif](https://upload-images.jianshu.io/upload_images/10769157-2129d1a3e61dcfa6.gif?imageMogr2/auto-orient/strip)

**Comment by 625781186** [comment]
能否显示楼层
