### ISSUE TITLE
打包  pyinstaller 里面的加密怎么使用呢？    

### ISSUE THREAD

**Issue by langmanyouling** [892768447/PyQt#16]
pyinstaller -key  并  16个字符串
--key=s424rrtgdfwlmndo

打包就报这样的错误

  File "/usr/local/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

**Comment by tonight-love** [comment]
Crypto这个库感觉目前很坑，对py3不友好
