### ISSUE TITLE
播放器

### ISSUE THREAD

**Issue by tonight-love** [892768447/PyQt#18]
基于 qtav 或者 迅雷 APlayer 的视频播放器

**Comment by 892768447** [comment]
PyQt QtAV player?

**Comment by tonight-love** [comment]
嗯嗯 可以结合 PyQt + QtAV 做一个播放器例子  。感觉 pyqt 在视频播放器方面还是空白

**Comment by 892768447** [comment]
1、看了下QtAV，要移植到PyQt需要时间
2、看了下迅雷的Aplayer是个com组件，PyQt可以用QAxWidget加载使用
3、说下APlayer，从官网下载sdk和解码器后解压出来，把解码器放到sdk\bin\codecs里面，然后用管理员权限运行install.bat注册com对象到系统中。
以下是简单调用播放视频文件。
```
app = QApplication(sys.argv)
w = QAxWidget('A9332148-C691-4B9D-91FC-B9C461DBE9DD')
w.show()
print(w.generateDocumentation()) # 这里是输出调用文档
w.dynamicCall("Open(QString)", r'D:\sintel.mp4'); #打开视频并播放
sys.exit(app.exec_())
```

暂时不考虑做这两个的例子。后期有时间把PyQt自带的多媒体播放做个例子

**Comment by tonight-love** [comment]
谢谢了，我当初想用这两个sdk的原因是因为qt 自带的多媒体播放是调用系统播放器，但是操作系统是不带有解码器的，需要手动安装解码器，而且我目前收集到的资料自带的多媒体是不能将解码器打包一起发布的，也就是说要使用这个播放器就必须安装解码器。这个让我有点不能接受，所以提出这个请求。

**Comment by 892768447** [comment]
1.qtav 可以用sip来封装为PyQt使用
2.我觉得既然Qt能从系统里找到解码器，肯定有个路径或者搜索地址，这样或许可以把解码器放程序目录里，加载

**Comment by tonight-love** [comment]
你说的第二点我也一直在看响应的方案，但是我这边一直没有找到这样的文档以及例子。

**Comment by 892768447** [comment]
### Media Players
* [Smplayer](http://smplayer.sourceforge.net/) — the original fully-featured Qt4/5 frontend for mplayer/mplayer2
* [mpv](http://mpv.io/) - A media player based on MPlayer and mplayer2. It supports a wide variety of video file formats, audio and video codecs, and subtitle types.
* [Vlc](http://www.videolan.org/vlc/) — Standalone media player
* [QMPlay2](http://qt-apps.org/content/show.php/QMPlay2?content=153339) — It can plays all formats and stream supported by ffmpeg and libmodplug. It has integrated Youtube browser.
* [Xt7-player](http://qt-apps.org/content/show.php/Xt7-player+3?content=151684) — Xt7 is an mplayer gui that aims to be a complete interface to its tons of options coded keeping usability in mind.

### Music Players
* [Cantata](https://code.google.com/p/cantata/) — Extremely featureful MPD client, with Qt4 and Qt5 interfaces.
* [Clementine](http://www.clementine-player.org/) — modern music player and library organiser inspired by Amarok 1.4.
* [YaRock](http://qt-apps.org/content/show.php?content=129372) — Modern Music Player with collection browser based on cover art.
* [Tomahawk](http://www.tomahawk-player.org/) — The social media player.
* [Musique](http://flavio.tordini.org/musique) — Music player with a clean and innovative interface.
* [Qmmp](http://qmmp.ylsoftware.com/) — Audio-player, the user interface is similar to winamp or xmms.
* [Quimup](http://coonsden.com/) —  A client for the Music Player Daemon (MPD) written in C++ and Qt
