### ISSUE TITLE
修改QFileSystemModel默认的ICON为自己自定义的ICON，或者把特定的ICON变成灰色。

### ISSUE THREAD

**Issue by dongzhang0725** [892768447/PyQt#2]
![qq 20180126110230](https://user-images.githubusercontent.com/15956921/35425641-40d4a972-0297-11e8-818d-f915638323ea.png)

**Comment by 892768447** [comment]
@dongzhang0725  https://github.com/892768447/PyQt/tree/master/%E7%95%8C%E9%9D%A2%E7%BE%8E%E5%8C%96/QFileSystemModel%E5%9B%BE%E6%A0%87
