### ISSUE TITLE
buttonTest函数实现动态sql语句以及显示

### ISSUE THREAD

**Issue by ymqian1785** [892768447/PyQt#20]
查询功能函数是buttonTest(self) 数据格式和航班数据在下面图片中显示 现在需要在buttonTest这个函数添加代码实现动态SQL语句，并将查询得到的结果显示在self.tableWidget 里
姓名对应self.checkBox和self.lineEdit 证件号对应self.checkBox_2和self.lineEdit_2 航班号对应self.checkBox_3和self.lineEdit_3 座位号对应self.checkBox_4和self.lineEdit_15 登机口对应self.checkBox_6和self.lineEdit_16 序号对应self.checkBox_8和self.lineEdit_17 
![default](https://user-images.githubusercontent.com/27682076/39910143-6922fd1e-5528-11e8-879d-35814853e1d4.JPG)
![default](https://user-images.githubusercontent.com/27682076/39910144-696a6604-5528-11e8-913e-2f6f7df1cc6f.JPG)
数据库链接语句为
self.conn = MySQLdb.connect( host='localhost', user='root', passwd='zdki', db='wenzhou', # charset='utf8', ) self.cur = self.conn.cursor() self.sqlstring = "select * from tourist2 where "

**Comment by ymqian1785** [comment]
![tablewidget](https://user-images.githubusercontent.com/27682076/39910318-494efeba-5529-11e8-9266-4b1714b1ae6d.JPG)
这是tableWidget格式

**Comment by 892768447** [comment]
https://github.com/892768447/PyQt/tree/master/%E6%95%B0%E6%8D%AE%E5%BA%93%E6%9F%A5%E8%AF%A2%E6%98%BE%E7%A4%BA%E8%A1%A8%E6%A0%BC
