### ISSUE TITLE
动态气泡提示？

### ISSUE THREAD

**Issue by xtvjxk123456** [892768447/PyQt#3]
我想要一个气泡提示的，就是qq 聊天记录那种，会在桌面右下角进行提示，竖排的气泡，旧内容的气泡随着新的内容自动上浮并一段时间后消失，下面一直上浮新的消息
像这样子
![image](https://user-images.githubusercontent.com/8720281/35435002-0ca3c282-02c4-11e8-8158-6b4e804e4339.png)

**Comment by 892768447** [comment]
@xtvjxk123456  简单写了下
https://github.com/892768447/PyQt/tree/master/%E6%B0%94%E6%B3%A1%E6%8F%90%E7%A4%BA
