### ISSUE TITLE
pyqt5插件例子

### ISSUE THREAD

**Issue by 625781186** [892768447/PyQt#4]
http://bbs.csdn.net/topics/370235978

**Comment by 892768447** [comment]
是使用PyQt去加载用Qt写的插件？
还是要自己实现插件接口？ @625781186

**Comment by 625781186** [comment]
使用pyqt实现pyqt的插件接口

**Comment by 892768447** [comment]
这个要看你怎么定义了：
1、类似Qt设计师的扩展widget插件
2、PyQt的界面插件
3、PyQt程序接口API 插件

**Comment by 625781186** [comment]
比如写了一款软件 ， 允许别人对程序功能扩展 ，应该属于第三种

**Comment by 892768447** [comment]
这个需要看你的app的主体功能和框架，不同情况可能会设计不同的插件模式，很少通用的框架。
