### ISSUE TITLE
影视浏览例子

### ISSUE THREAD

**Issue by gaoyan2659365465** [892768447/PyQt#6]
像腾讯视频那样的排版，用pyqt5和html加css组成

**Comment by 892768447** [comment]
没有使用html哦，全部是自定义widget
https://github.com/892768447/PyQt/tree/master/%E8%85%BE%E8%AE%AF%E8%A7%86%E9%A2%91%E7%83%AD%E6%92%AD%E5%88%97%E8%A1%A8
