### ISSUE TITLE
pyqt5 使用QAxWidget怎么显示Microsoft Word？

### ISSUE THREAD

**Issue by Timessence** [892768447/PyQt#7]
萌新请教~使用QAxWidget能显示Word，但打不开指定的.docx文件。。
![qq 20180313224107](https://user-images.githubusercontent.com/33260212/37348688-b5ba5aba-270f-11e8-9d62-8b2e9adc8bf3.png)

**Comment by Timessence** [comment]
http://blog.csdn.net/zy19940906/article/details/61426429#一qaxwidget操作office
在pyqt照写后打不开。。。。

**Comment by 892768447** [comment]
试试呢。

```#!/usr/bin/env python
# -*- coding: utf-8 -*-
from PyQt5.QAxContainer import QAxWidget
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QPushButton, QFileDialog


class Window(QWidget):

    def __init__(self, *args, **kwargs):
        super(Window, self).__init__(*args, **kwargs)
        layout = QVBoxLayout(self)
        self.axWidget = QAxWidget('Word.Applicatio', self)
        layout.addWidget(self.axWidget)
        layout.addWidget(QPushButton('打开word', self, clicked=self.onOpenWord))

    def onOpenWord(self):
        path, _ = QFileDialog.getOpenFileName(
            self, '请选择Word文件', '', 'word(*.docx *.doc)')
        if not path:
            return
        # 不显示窗体
        self.axWidget.dynamicCall('SetVisible (bool Visible)', 'false')
        self.axWidget.setProperty('DisplayAlerts', False)
        self.axWidget.setControl(path)


if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication
    app = QApplication(sys.argv)
    w = Window()
    w.show()
    sys.exit(app.exec_())
```

**Comment by Timessence** [comment]
@892768447 非常感谢群主的帮助~谢谢~新人不太会用gayhub，还请见谅~

**Comment by FengZhiheng** [comment]
> 试试呢。
> 
> ```
> # -*- coding: utf-8 -*-
> from PyQt5.QAxContainer import QAxWidget
> from PyQt5.QtWidgets import QWidget, QVBoxLayout, QPushButton, QFileDialog
> 
> 
> class Window(QWidget):
> 
>     def __init__(self, *args, **kwargs):
>         super(Window, self).__init__(*args, **kwargs)
>         layout = QVBoxLayout(self)
>         self.axWidget = QAxWidget('Word.Applicatio', self)
>         layout.addWidget(self.axWidget)
>         layout.addWidget(QPushButton('打开word', self, clicked=self.onOpenWord))
> 
>     def onOpenWord(self):
>         path, _ = QFileDialog.getOpenFileName(
>             self, '请选择Word文件', '', 'word(*.docx *.doc)')
>         if not path:
>             return
>         # 不显示窗体
>         self.axWidget.dynamicCall('SetVisible (bool Visible)', 'false')
>         self.axWidget.setProperty('DisplayAlerts', False)
>         self.axWidget.setControl(path)
> 
> 
> if __name__ == '__main__':
>     import sys
>     from PyQt5.QtWidgets import QApplication
>     app = QApplication(sys.argv)
>     w = Window()
>     w.show()
>     sys.exit(app.exec_())
> ```
我们遇到什么困难：
ModuleNotFoundError: No module named 'PyQt5.QAxContainer'

**Comment by Galaxyjia** [comment]
mac 电脑上显示 No module named 'PyQt5.QAxContainer

**Comment by 892768447** [comment]
> mac 电脑上显示 No module named 'PyQt5.QAxContainer

这只有win上才有的com对象

**Comment by copperyp** [comment]
> 
> 
> 试试呢。
> 
> ```
> # -*- coding: utf-8 -*-
> from PyQt5.QAxContainer import QAxWidget
> from PyQt5.QtWidgets import QWidget, QVBoxLayout, QPushButton, QFileDialog
> 
> 
> class Window(QWidget):
> 
>     def __init__(self, *args, **kwargs):
>         super(Window, self).__init__(*args, **kwargs)
>         layout = QVBoxLayout(self)
>         self.axWidget = QAxWidget('Word.Applicatio', self)
>         layout.addWidget(self.axWidget)
>         layout.addWidget(QPushButton('打开word', self, clicked=self.onOpenWord))
> 
>     def onOpenWord(self):
>         path, _ = QFileDialog.getOpenFileName(
>             self, '请选择Word文件', '', 'word(*.docx *.doc)')
>         if not path:
>             return
>         # 不显示窗体
>         self.axWidget.dynamicCall('SetVisible (bool Visible)', 'false')
>         self.axWidget.setProperty('DisplayAlerts', False)
>         self.axWidget.setControl(path)
> 
> 
> if __name__ == '__main__':
>     import sys
>     from PyQt5.QtWidgets import QApplication
>     app = QApplication(sys.argv)
>     w = Window()
>     w.show()
>     sys.exit(app.exec_())
> ```

self.axWidget = QAxWidget('Word.Applicatio', self) => self.axWidget = QAxWidget('Word.Application', self)

every thing ok, in my windows10 + office 16.0.xxxx
